### ISSUE TITLE
Internal routine functions

### ISSUE THREAD

**Issue by rvignolo** [seamplex/wasora#2]
Hi, 

I want to create a `function_t` object within a wasora plugin capable of calling an internal routine to compute f(**x**) values. I am aware it could be done with the `type_routine` function. However, `function_t` has a pointer with  `double (*routine)(const double *)` prototype and I would need something like `double (*internal_routine)(void *)` since I have to provide a complex structure as argument to compute the function value.  

Do you think adding this prototype to the `function_t` structure is a good idea? This would also mean that we will have a new function type like `type_internal_routine`. Any thoughts?

**Comment by gtheler** [comment]
No. Adding anything else like a pointer to `void` means that such function will not be callable from a wasora input file and only from a plugin. Create a wrapper structure containing your pointer plus the pointer to the `function_t` structure you need and add whatever complexity you need to add inside your plugin and not in the wasora code.

For instance, if you need a pointer to a generic structure which is unique to the function f(x) you can hash the function name and use that index to search into a global hash of pointers to void, initialized in the `init()` part of your plugin.

**Comment by rvignolo** [comment]
Oh that's right! Amazing, thank you!

**Comment by rvignolo** [comment]
Wait... suppose the following scheme:

```C
struct plugin_object_t {
  // ...
  function_t *a;
  function_t *b;

  double *r;

  function_t *P;
  // ...
  UT_hash_handle hh;
};

struct {
  // ...
  plugin_object_t *plugin_objects;
  // ...
} plugin_name;

```
Suppose that a `plugin_object_t` is created during parsing time depending on an input instruction. It will be located in the global hash "table" `plugin_objects`. Also, this object creates some `function_t` structures that will be located in the wasora's `functions` table. However, while functions `a` and `b` will be filled during the execution of the instruction that created the `plugin_object`, `P` is a routine function that must call a routine that uses `a`, `b`, `r` and the `x` provided by the user in the input file. I mean, I need that `P` can be invoked by the used in input file.

I don't know how to code a routine function accepted by wasora's `function_t` structure that searches the needed functions `a` and `b` or better, the `plugin_object` by name because those routines do not accept anything else than a `double *` argument. 

Help!

**Comment by gtheler** [comment]
they are global, just include the needed header files in your source code and access the global structures, no need to pass anything as a pointer

**Comment by rvignolo** [comment]
No, I know that, but I will need to search the needed functions in the
table of wasora's functions by name but I won't know the name of those
functions at compiling time.

That is the problem, those names are generated at running time and that is
why I do not know how to code the routine function

**Comment by gtheler** [comment]
you cannot know them at compiling time but you will at parsing time, so in your plugin's `init_after_parser` you can know everything you need to know. So write this information into the global structure and then let your callable function to read such information from the global structure each time it is evaluated.

**Comment by rvignolo** [comment]
So let's suppose I am at `init_after_parser`. At this point, I have already defined (not initialized) all the functions because the `plugin_define_plugin_object` function has been already called in the parser. I have defined those needed functions in the `plugin_define_plugin_object`, but I understand that you want me to move them into the `init_after_parser` instruction. I cannot do that because at that point the whole input has been parsed and I might have used an expression containing those functions.

The problem is the name of those functions. There is not only one function named `phi` like in milonga (defined when parsing the `MILONGA_PROBLEM` instruction), but there might be several functions `P`, one for each object created. I mean, if in the input file there are several instructions of the same type that build a `plugin_object_t`, I will have several functions `P`. Each of them is named P_<plugin_instruction_object_name> and can be called in the input file. For example:
```
PLUGIN_INSTRUCTION NAME dummy_1 ...
PLUGIN_INSTRUCTION NAME dummy_2 ...

PRINT_FUNCTION a_dummy_1 b_dummy_1 P_dummy_1 a_dummy_2 b_dummy_2 P_dummy_2
```
The parsing of `PLUGIN_INSTRUCTION` defines a `plugin_object_t` (which also defines the pertinent `function_t` functions). Then, each `PLUGIN_INSTRUCTION` instruction builds the object of type `plugin_object_t`  and fill the arguments and values of the functions `a` and `b`. 

When I want to evaluate `P_dummy_1(0.1,1.0)` I have to call a routine which has to be able to call functions `a_dummy_1` and `b_dummy_1`. That is the problem.

You see what I mean?

**Comment by gtheler** [comment]
I do now. I somehow though that the called function was able to access its name, hence I said you could hash the name in the function itself. Now I think that the name of the wasora function is not known within the C routine. Let me get back at you.

**Comment by rvignolo** [comment]
Exactly, everything would be fine if the C routine has access to the name of the function. Thank you!

**Comment by gtheler** [comment]
ok, make a pull request with your idea and I will take a look at it and eventually approve it
