### ISSUE TITLE
parsing expressions in wasora

### ISSUE THREAD

**Issue by rvignolo** [seamplex/wasora#4]
is there any way I can ask wasora to tell me which objects are present in an expression? 

specifically, I have the following code:

```
T = 1.0
K = 0.5

S(t) := sin(t)

V(t) := max(S(t) - K, 0)

DERIVATIVE NAME call PAYOFF V(T) ...
```

The secondary keyword PAYOFF expects a wasora expression that will be stored internally in a pointer to `expr_t` structure. How would you code a function that returns all the functions present in the expression V(T)? The expected result would be the `function_t *` objects with names V and S.

Thanks!

**Comment by gtheler** [comment]
loop over `factor_t *token` which is an array of size `n_tokens` and see if the `type` is `EXPR_FUNCTION`. If it is, see which function it is by looking at the pointer `function_t *function`.

**Comment by rvignolo** [comment]
perfect

additionally, if the function is of type `type_algebraic`, apply recursion, right?

Will code it

**Comment by gtheler** [comment]
probably, I haven't thought about that

I now understand why you want to get both V and S.

BTW, watch the name of the keywords. `DERIVATIVE` seems a pretty general one. Particular instructions are usually preprended by the plugin's name such as `FINO_SOLVE` or `MILONGA_SCHEME`

**Comment by rvignolo** [comment]
Yes, `DERIVATIVE` seems a pretty general keyword. But for a [Quant ](https://en.wikipedia.org/wiki/Quantitative_analyst)it is [not](https://en.wikipedia.org/wiki/Derivative_(finance)). Moreover, It might be really annoying to write something like `KOSMOS_DERIVATIVE`, it would feel like writing `WASORA_VECTOR`.

But of course I might eventually change it! Thanks!

**Comment by rvignolo** [comment]
oh, it is not that easy

for example, if the token is of type `EXPR_BUILTIN_FUNCTION` I will have to loop over it arguments as well.

:)

**Comment by rvignolo** [comment]
Jeremy,

I noticed a really strange behavior in wasora that may require an important fix. Suppose you have an expression such as `sin(0.1)` and you want to loop over the arguments of the builtin function `sin`. There should be only one argument, i.e., `0.1`. However, I have noticed that there are always others arguments with chaotic behavior. 

Please, refer clone this [fork](https://github.com/rvignolo/wasora/tree/expr-args) and checkout the `expr-args` branch. You will find a MWE `nfunctions.was` that will lead to a Segmentation fault. Please, debug the instruction, paying particular attention to this part:

``` C
for (j = 0; j < MINMAX_ARGS; j++) {
    
    if (expr->token[i].arg[j].n_tokens != 0)
        wasora_call(wasora_count_expression_functions(&expr->token[i].arg[j], n));
 }
```

when `expr->token[i]` is the builtin function `sin`, there should be only one argument. So, for `j=1` we would expect to see that `n_tokens` equal to zero. This is not the case. 

Thanks!
