### ISSUE TITLE
integral over semi-infinite interval

### ISSUE THREAD

**Issue by rvignolo** [seamplex/wasora#6]
I wanted to compute the Bivariate Normal joint pdf with wasora. So I just typed: 
```
N(x,y) := integral(integral(1 / (2 * pi * sqrt(1 - rho^2)) * exp(-(u^2 - 2 * rho * u * v + v^2) / (2 * (1 - rho^2))), v, -infinite, y), u, -infinite, x)
```
But it failed to compute the true value. I had to increment the integration interval, because wasora checks:
```C
} else if (x_lower < -wasora_var(wasora_special_var(infinite))) {
```
in order to call `gsl_integration_qagil` routine. 

I could not define the correct function since I used that exact same value as lower limit in the integral. Of course, the quick solution is to decrement the interval lower limit in the input file. Shouldn't we change the code instead?:
```C
} else if (x_lower < -wasora_var(wasora_special_var(infinite) + dx)) {
```

**Comment by gtheler** [comment]
sure, actually I wrote that but never used it myself

**Comment by gtheler** [comment]
feel free to make any changes you wish in this regard

**Comment by rvignolo** [comment]
will do, thanks!
