### ISSUE TITLE
gsl_sort_vector2 implementation

### ISSUE THREAD

**Issue by rvignolo** [seamplex/wasora#7]
Hi,

I want to implement an instruction that uses [this](https://www.gnu.org/software/gsl/doc/html/sort.html#c.gsl_sort2) gsl function. Wasora's similar instruction, `VECTOR_SORT`, receives only one argument, i.e., a `vector_t` structure. However, in this case, we need to receive at least two `vector_t` objects. 

Should we implement a new structure that accounts for this case? 

We could implement something more general for both instructions or collapse both cases to the same instruction. What do you think? What about something like this:

```C
struct sortedvector_t {
  vector_t *v1;
  vector_t *v2;

  int ascending;   // order type, i.e. ascending or descending numerical order
}
```
?

**Comment by gtheler** [comment]
make the struct as general as possible, unused pointer will be null

**Comment by rvignolo** [comment]
I  have incorporated those changes but cannot share them with you at the moment since:
1. I do not have write access to the main respository
2. I have already forked wasora but I have been using that version for changes in order to use wasora in cygwin... So I cannot make a clean pull request at the moment

Although, I have pushed those changes in my [repository](https://github.com/rvignolo/wasora).

**Comment by gtheler** [comment]
you now belong to the wasora team that has write access
